### PR TITLE
Fix date

### LINKED ISSUE #10: month number in share text is one month behind

### PR DESCRIPTION
**Pull request by valanm22**
Fixes #10

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -308,7 +308,7 @@ function share(inputGame){
         }
     }
 
-    shareStr = "Вордел "+[d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()].join('-')+'\n'+shareStr
+    shareStr = "Вордел "+[d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate()].join('-')+'\n'+shareStr
```
Comment (valanm22) [inline main.js:311]: @svvvst the `getmonth()` function returns the month as a number between 0 and 11. So I've incremented the value by one to match your date format.

Comment (svvvst) [reply main.js:311]: Thanks for your help! Didn't have a chance to get around to this!
